#!/bin/bash

echo "~~~ analyzer-buildkite-plugin :: environment hook"

echo "trying to run a python script inside the plugin"
python "$(dirname ${BASH_SOURCE})/../scripts/analyze.py"

echo "buildkite bin path: $BUILDKITE_BIN_PATH"
rm -rf "${BUILDKITE_BIN_PATH}/analyze"
ln -s "$(dirname ${BASH_SOURCE})/../scripts/analyze.py" "${BUILDKITE_BIN_PATH}/analyze"

echo "testing symlinking binary to python file" 
which analyze
analyze
