#!/bin/bash

set -x

echo "~~~ analyzer-buildkite-plugin :: environment hook"

bin_dir=$(pwd)/bin
mkdir -p $bin_dir
rm -rf "${bin_dir}/analyze"
ln -s "$(dirname ${BASH_SOURCE})/../scripts/analyze.py" "${bin_dir}/analyze"
export PATH=$PATH:$bin_dir
