#!/bin/bash

set -euo pipefail

echo "~~~ installing analyzer in analyzer-buildkite-plugin"

bin_dir=$(pwd)/bin
mkdir -p $bin_dir
rm -rf "${bin_dir}/analyze"
ln -s "$(dirname ${BASH_SOURCE})/../scripts/analyze.py" "${bin_dir}/analyze"
export PATH=$PATH:$bin_dir
